name: Create Distro

on: 
  push:
    branches:
    - test_actions

jobs:
  Linux-Distro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: NPM install
        shell: bash
        run: |
          cd /home/runner/work/izzzio/izzzio
          npm install

      - name: create zip distro
        shell: bash
        run: |
          cp $(which node) /home/runner/work/izzzio/izzzio/.
          cd /home/runner/work/izzzio/
          zip -r izzzio.zip izzzio/*

      - name: Upload Linux distro
        uses: actions/upload-artifact@v1
        with:
          name: iz3node-linux-x64.zip
          path: /home/runner/work/izzzio/izzzio.zip
          
  Get-Windows-Node-Files:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: npm install
        shell: cmd
        run: npm install "d:\a\izzzio\izzzio"
          
      - name: Upload windows distro
        uses: actions/upload-artifact@v1
        with:
          name: win-node-exe
          path: "c:\\Program Files\\nodejs\\node.exe"

      - name: Upload Node Modules for Windows
        uses: actions/upload-artifact@v1
        with: 
          name: win-node-modules
          path: node_modules

  Build-Windows-Distro:
    needs: Get-Windows-Node-Files
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - name: Get Windows Node exe
        uses: actions/download-artifact@v1
        with: 
          name: win-node-exe
      
      - name: Get Windows Node modules
        uses: actions/download-artifact@v1
        with: 
          name: win-node-modules

      - name: ZIP IT
        shell: bash
        run: |
          cd /home/runner/work/izzzio/
          zip -r izzzio.zip izzio/*

      - name: Upload Windows Distro
        uses: actions/upload-artifact@v1
        with: 
          name: iz3node-linux-x64.zip
          path: /home/runner/work/izzzio/izzzio.zip