name: Test

on: 
  push:
    branches:
    - test_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: echo Hello World and save file
        shell: bash
        run: which node > tree.txt
      - name: Test upload 
        uses: actions/upload-artifact@v1
        with:
          name: test_file
          path: tree.txt
      