name: Test

on: 
  push:
    branches:
    - test_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello World and save file
        shell: bash
        run: ls -a ~/work > tree.txt
      - name: Test upload 
        uses: actions/upload-artifact@v1
        with:
          name: test_file
          path: tree.txt
      