name: Test

on: 
  push:
    branches:
    - test_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello World and save file
        shell: bash
        run: mkdir test_test/; echo "Hello World" > test_test/test_test_test_test.test
      - name: Test upload 
        uses: actions/upload-artifact@v1
        with:
          name: test_file
          path: test_test/test_test_test_test.test
      