name: Zips

on: 
  push:
    branches:
    - test_actions
    tags:
    - 'v*.*.*'

jobs:
  Linux-Distro:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: NPM install
        shell: bash
        run: |
          cd /home/runner/work/izzzio/izzzio
          npm install

      - name: create zip distro
        shell: bash
        run: |
          cp $(which node) /home/runner/work/izzzio/izzzio/.
          cd /home/runner/work/izzzio/
          zip -r izzzio.zip izzzio/*

      - name: Upload Linux distro
        uses: actions/upload-artifact@v1
        with:
          name: iz3node-linux-x64.zip
          path: /home/runner/work/izzzio/izzzio.zip

  Get-Windows-Node-Exe:
    runs-on: windows-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: node install
        shell: cmd
        run: |
          node.exe install
          
      - name: Copy nodejs.exe
        shell: cmd
        run: |
          cp "c:\Program Files\nodejs\node.exe" "d:\a\izzzio\izzzio\node.exe"

      - name: Upload windows distro
        uses: actions/upload-artifact@v1
        with:
          name: win-node-exe
          path: "c:\\Program Files\\nodejs\\node.exe"

      - name: Check izzzio dir
        shell: cmd
        run: dir "d:\a\izzzio\izzzio\" > test_dir.txt

      - name: Upload test file
        uses: actions/upload-artifact@v1
        with:
          name: test-file
          path: test_dir.txt

      - name: Upload Node Modules for Windows
        uses: actions/upload-artifact@v1
        with: 
          name: win-node-modules
          path: "d:\\a\\izzzio\\izzzio\\node_modules"