name: Zips

on: 
  push:
    branches:
    - test_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: create zip distro
        shell: bash
        run: |
          cp $(which node) /home/runner/work/izzzio/izzzio/. 
          zip -r izzzio.zip /home/runner/work/izzzio/izzzio/*
      - name: Test upload 
        uses: actions/upload-artifact@v1
        with:
          name: test_file
          path: izzzio.zip
      