name: Zip Win

on: 
  push:
    branches:
    - test_actions
    tags:
    - 'v*.*.*'

  Get-Windows-Node-Exe:
    runs-on: windows-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: npm install
        shell: cmd
        run: npm install

      - name: Upload test file
        uses: actions/upload-artifact@v1
        with:
          name: test-file
          path: test.txt
          
      - name: Upload windows distro
        uses: actions/upload-artifact@v1
        with:
          name: win-node-exe
          path: "c:\\Program Files\\nodejs\\node.exe"

      - name: Upload Node Modules for Windows
        uses: actions/upload-artifact@v1
        with: 
          name: win-node-modules
          path: node_modules