name: Zip Win

on: 
  push:
    branches:
    - test_actions

jobs:
  Get-Windows-Node-Exe:
    runs-on: windows-2019
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: npm install
        shell: cmd
        run: npm install "d:\a\izzzio\izzzio"
          
      - name: Upload windows distro
        uses: actions/upload-artifact@v1
        with:
          name: win-node-exe
          path: "c:\\Program Files\\nodejs\\node.exe"

      - name: Upload Node Modules for Windows
        uses: actions/upload-artifact@v1
        with: 
          name: win-node-modules
          path: node_modules